### ISSUE TITLE
About the choice of key and value

### ISSUE THREAD

**Issue by Zain-Jiang** [mutiann/neural-lexicon-reader#1]
Thanks a lot for publishing your wonderful work. In you paper, "In our experiments,
we use pretrained XLM-R as the knowledge encoder, using its final-layer embeddings as keys to represent semantic
information. They are then concatenated with the first-layer
embeddings as values to inject shallow character identities." However, in your code, you take the first-layer
embeddings as keys.

**Comment by Zain-Jiang** [comment]
Thanks a lot for publishing your wonderful work. In you paper, "In our experiments,
we use pretrained XLM-R [9] as the knowledge encoder, using its final-layer embeddings as keys to represent semantic
information. They are then concatenated with the first-layer
embeddings as values to inject shallow character identities." However, in your code, you take the first-layer
embeddings as keys.

**Comment by mutiann** [comment]
Sorry for the mistake in the paper. The key is actually the first-layer embeddings to represent character identities.
